config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  'groups#index'   #ルートパスの指定

    resources :groups , only: [:new, :create, :edit,:update] do
      resources :messages, only: [:index, :create]
    end
    resources :users, only: [:edit, :update, :index] 
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true, uniqueness: true

def show_last_message
  if (last_message = messages.last).present?
    last_message.content? ? last_message.content : '画像が投稿されています'
  else
    'まだメッセージはありません。'
  end
end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :content, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

   protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  
    def new
      @group = Group.new
      @group.users << current_user
    end
  
    def create
      @group = Group.new(group_params)
      @group.users << current_user
      if @group.save
        redirect_to root_path, notice: 'グループを作成しました'
      else
        render :new
      end
    end
  
    def update
      if @group.update(group_params)
        redirect_to group_messages_path(@group), notice: 'グループを編集しました'
      else
        render :edit
      end
    end
  
    private
    def group_params
      params.require(:group).permit(:name, { user_ids: [] })
    end
  
    def set_group
      @group = Group.find(params[:id])
    end
  end
  

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    @members = @group.users
    respond_to do |format|
      format.html
      format.json { @messages = @messages.where("id > ?", params[:last_id]) }
    end
 
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController

    def index
      @users = User.where('name LIKE(?)', "%#{params[:name]}%").where.not(id: current_user.id)
      respond_to do |format|
        format.html
        format.json
      end
    end
    
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix

    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
     
    #chat-group-users
      #chat-group-user-22.chat-group-user.clearfix
        %input{name: "chat_group[user_ids][]",type: "hidden", value: "22"}
        %p.chat-group-user__name

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  .chat__side
    = render partial: "messages/chat_side_top"
    = render partial: "messages/chat_side_glist"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_chat_main_footer.html.haml
.main__footer
  = form_for [@group, @message] do |f|
    = f.text_field :content, class: 'main__footer__text', placeholder: 'type a message'
    .main__footer__form__mask
      = f.label :image, class: 'form__mask__image' do
        = fa_icon 'picture-o', class: 'icon'
        = f.file_field :image, class: 'hidden'
    = f.submit 'Send', class: 'main__footer__send-button'

app/views/messages/_chat_main_header.html.haml
.chat__main__header
  .chat__main__header__gname
    = @group.name
    .chat__main__header__member
      メンバー:
      - @members.each do |member|
        = member.name
  .chat__main__header__edit-button
    = link_to "Edit", edit_group_path(params[:group_id]), method: :get

app/views/messages/_chat_main_message.html.haml
.main__message__box{"data-message-id": "#{message.id}"}
  .main__message__box__top
    .main__message__box__top__name
      = message.user.name
    .main__message__box__top__time
      = message.created_at.time.to_s(:datetime)
  .main__message__box__text
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/_chat_side_glist.html.haml
.chat__side__glist
  - current_user.groups.each do |group|  
    .chat__side__glist__group    
      = link_to group_messages_path(group) do
        .chat__side__glist__group__name
          = group.name
        .chat__side__glist__group__message
          = group.show_last_message

app/views/messages/_chat_side_top.html.haml
.chat__side__top
  .chat__side__top__user-name
    = current_user.name
  .chat__side__top__icon
    = link_to new_group_path do
      = fa_icon 'pencil-square-o', class: 'icon'
    = link_to edit_user_path(current_user) do
      = fa_icon 'cog', class: 'icon'
      

app/views/messages/index.html.haml
.chat
  .chat__side
    = render partial: "chat_side_top"
    = render partial: "chat_side_glist"
  .chat__main
    .chat__main__border
    = render partial: "chat_main_header"
    .main__message
      - @messages.each do |m|
        = render partial: "chat_main_message", locals: {message: m}
      = render partial: "chat_main_footer"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'